version: '3.9'

services:
    pharmlinetestingsystem:
        image: sardor557/pharmlinetestingsystem:latest
        ports:
            - "27850:27850"           
        environment:
            - ASPNETCORE_URLS=http://0.0.0.0:27850

    nginx:
        image: nginx:stable-alpine
        ports:
          - "27851:27851"
        volumes:
          - my_nginx:/etc/nginx/nginx.conf:ro
        depends_on:
          - pharmlinetestingsystem

volumes:
    my_nginx:
        name: my_nginx